theme: jekyll-theme-cayman
title: Michael Yusheng Wu
description: Michael is currently a PhD student at the University of Kansas studying performance management and machine learning in the Department of Public Administration.
